"""add fx_use_historical_rates to user

Revision ID: 4b1464fbd894
Revises: 23f885177bf1
Create Date: 2026-05-27 15:50:30.986892

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision: str = '4b1464fbd894'
down_revision: Union[str, Sequence[str], None] = '23f885177bf1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('fx_use_historical_rates', sa.Boolean(), nullable=False, server_default='false'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'fx_use_historical_rates')
    # ### end Alembic commands ###
