"""add language to user

Revision ID: d1ba3b7fc6e2
Revises: f27b138cdc86
Create Date: 2026-05-04 10:16:36.649321

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision: str = "d1ba3b7fc6e2"
down_revision: Union[str, Sequence[str], None] = "f27b138cdc86"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users", sa.Column("language", sqlmodel.sql.sqltypes.AutoString(length=10), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "language")
    # ### end Alembic commands ###
