"""add attachment_model to ai_providers

Revision ID: 731672a281f9
Revises: 856a907219ce
Create Date: 2026-07-18 11:02:40.353080

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision: str = "731672a281f9"
down_revision: Union[str, Sequence[str], None] = "856a907219ce"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "ai_providers",
        sa.Column("attachment_model", sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("ai_providers", "attachment_model")
    # ### end Alembic commands ###
