"""add_user_custom_ai_prompt

Revision ID: e99074fad2c7
Revises: 9c43f7f95f64
Create Date: 2026-04-18 19:09:19.041390

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision: str = "e99074fad2c7"
down_revision: Union[str, Sequence[str], None] = "9c43f7f95f64"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users",
        sa.Column("custom_ai_prompt", sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "custom_ai_prompt")
    # ### end Alembic commands ###
