"""make display_name nullable

Revision ID: 23f885177bf1
Revises: add_chat_model_to_ai_providers
Create Date: 2026-05-21 08:33:48.002663

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision: str = "23f885177bf1"
down_revision: Union[str, Sequence[str], None] = "add_chat_model_to_ai_providers"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("users", "display_name", existing_type=sa.VARCHAR(length=100), nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("users", "display_name", existing_type=sa.VARCHAR(length=100), nullable=False)
    # ### end Alembic commands ###
