"""cascade delete transaction_tags on tag delete

Revision ID: f5afe3c7e436
Revises: d1ba3b7fc6e2
Create Date: 2026-05-05 20:17:15.678104

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision: str = 'f5afe3c7e436'
down_revision: Union[str, Sequence[str], None] = 'd1ba3b7fc6e2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('expense_tags_tag_id_fkey'), 'transaction_tags', type_='foreignkey')
    op.create_foreign_key(None, 'transaction_tags', 'tags', ['tag_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'transaction_tags', type_='foreignkey')
    op.create_foreign_key(op.f('expense_tags_tag_id_fkey'), 'transaction_tags', 'tags', ['tag_id'], ['id'])
    # ### end Alembic commands ###
