import {
  Utensils,
  Car,
  Home,
  Clapperboard,
  Pill,
  Plane,
  BookOpen,
  Dumbbell,
  ShoppingBag,
  Lightbulb,
  Gamepad2,
  Coffee,
  Pizza,
  Music,
  Briefcase,
  Heart,
  Gift,
  Shirt,
  Bus,
  Wifi,
  Phone,
  Baby,
  PawPrint,
  Wrench,
  Landmark,
  GraduationCap,
  Bike,
  Train,
  Fuel,
  Scissors,
  Stethoscope,
  ShoppingCart,
  Tv,
  Leaf,
  Wallet,
  TrendingUp,
  Soup,
  IceCream2,
  Wine,
  Beer,
  Sandwich,
  Apple,
  Salad,
  ChefHat,
  Truck,
  Ship,
  Sailboat,
  Caravan,
  ParkingCircle,
  MapPin,
  Navigation,
  Building2,
  Building,
  Hotel,
  Tent,
  Sofa,
  Lamp,
  Bath,
  Hammer,
  Paintbrush,
  Zap,
  Droplets,
  Thermometer,
  Flame,
  Smartphone,
  Laptop,
  Monitor,
  Headphones,
  Camera,
  Printer,
  Watch,
  Tablet,
  Syringe,
  Activity,
  Brain,
  Eye,
  Smile,
  Bone,
  FlaskConical,
  Microscope,
  Trophy,
  Medal,
  Volleyball,
  Footprints,
  Mountain,
  Waves,
  Snowflake,
  Sun,
  Umbrella,
  Palette,
  Pen,
  Newspaper,
  Library,
  Globe,
  Languages,
  Rocket,
  Star,
  Sparkles,
  PartyPopper,
  Cake,
  Balloon,
  Handshake,
  Users,
  UserRound,
  Crown,
  Diamond,
  Gem,
  CircleDollarSign,
  PiggyBank,
  CreditCard,
  Receipt,
  BarChart2,
  LineChart,
  DollarSign,
  Euro,
  Coins,
  Banknote,
  Package,
  Archive,
  Box,
  Boxes,
  Tag,
  Tags,
  Ticket,
  QrCode,
  type LucideIcon,
} from 'lucide-react';

export const CATEGORY_ICONS: { name: string; icon: LucideIcon; label: string }[] = [
  { name: 'Utensils', icon: Utensils, label: 'Food' },
  { name: 'Coffee', icon: Coffee, label: 'Coffee' },
  { name: 'Pizza', icon: Pizza, label: 'Pizza' },
  { name: 'Soup', icon: Soup, label: 'Soup' },
  { name: 'IceCream2', icon: IceCream2, label: 'Ice cream' },
  { name: 'Wine', icon: Wine, label: 'Wine' },
  { name: 'Beer', icon: Beer, label: 'Beer' },
  { name: 'Sandwich', icon: Sandwich, label: 'Sandwich' },
  { name: 'Apple', icon: Apple, label: 'Fruits' },
  { name: 'Salad', icon: Salad, label: 'Salad' },
  { name: 'ChefHat', icon: ChefHat, label: 'Cooking' },
  { name: 'ShoppingCart', icon: ShoppingCart, label: 'Groceries' },
  { name: 'ShoppingBag', icon: ShoppingBag, label: 'Shopping' },
  { name: 'Shirt', icon: Shirt, label: 'Clothing' },
  { name: 'Car', icon: Car, label: 'Car' },
  { name: 'Bus', icon: Bus, label: 'Transit' },
  { name: 'Train', icon: Train, label: 'Train' },
  { name: 'Bike', icon: Bike, label: 'Bike' },
  { name: 'Plane', icon: Plane, label: 'Travel' },
  { name: 'Fuel', icon: Fuel, label: 'Fuel' },
  { name: 'Truck', icon: Truck, label: 'Truck' },
  { name: 'Ship', icon: Ship, label: 'Ship' },
  { name: 'Sailboat', icon: Sailboat, label: 'Sailboat' },
  { name: 'Caravan', icon: Caravan, label: 'Caravan' },
  { name: 'ParkingCircle', icon: ParkingCircle, label: 'Parking' },
  { name: 'MapPin', icon: MapPin, label: 'Location' },
  { name: 'Navigation', icon: Navigation, label: 'Navigation' },
  { name: 'Home', icon: Home, label: 'Housing' },
  { name: 'Building2', icon: Building2, label: 'Office' },
  { name: 'Building', icon: Building, label: 'Building' },
  { name: 'Hotel', icon: Hotel, label: 'Hotel' },
  { name: 'Tent', icon: Tent, label: 'Camping' },
  { name: 'Sofa', icon: Sofa, label: 'Furniture' },
  { name: 'Lamp', icon: Lamp, label: 'Lamp' },
  { name: 'Bath', icon: Bath, label: 'Bathroom' },
  { name: 'Hammer', icon: Hammer, label: 'Tools' },
  { name: 'Paintbrush', icon: Paintbrush, label: 'Painting' },
  { name: 'Lightbulb', icon: Lightbulb, label: 'Utilities' },
  { name: 'Zap', icon: Zap, label: 'Electricity' },
  { name: 'Droplets', icon: Droplets, label: 'Water' },
  { name: 'Thermometer', icon: Thermometer, label: 'Temperature' },
  { name: 'Flame', icon: Flame, label: 'Gas' },
  { name: 'Wifi', icon: Wifi, label: 'Internet' },
  { name: 'Phone', icon: Phone, label: 'Phone' },
  { name: 'Tv', icon: Tv, label: 'Streaming' },
  { name: 'Smartphone', icon: Smartphone, label: 'Smartphone' },
  { name: 'Laptop', icon: Laptop, label: 'Laptop' },
  { name: 'Monitor', icon: Monitor, label: 'Monitor' },
  { name: 'Headphones', icon: Headphones, label: 'Headphones' },
  { name: 'Camera', icon: Camera, label: 'Camera' },
  { name: 'Printer', icon: Printer, label: 'Printer' },
  { name: 'Watch', icon: Watch, label: 'Watch' },
  { name: 'Tablet', icon: Tablet, label: 'Tablet' },
  { name: 'Pill', icon: Pill, label: 'Medicine' },
  { name: 'Stethoscope', icon: Stethoscope, label: 'Health' },
  { name: 'Heart', icon: Heart, label: 'Wellness' },
  { name: 'Dumbbell', icon: Dumbbell, label: 'Fitness' },
  { name: 'Syringe', icon: Syringe, label: 'Vaccine' },
  { name: 'Activity', icon: Activity, label: 'Activity' },
  { name: 'Brain', icon: Brain, label: 'Mental health' },
  { name: 'Eye', icon: Eye, label: 'Vision' },
  { name: 'Smile', icon: Smile, label: 'Dental' },
  { name: 'Bone', icon: Bone, label: 'Orthopedic' },
  { name: 'FlaskConical', icon: FlaskConical, label: 'Lab' },
  { name: 'Microscope', icon: Microscope, label: 'Science' },
  { name: 'BookOpen', icon: BookOpen, label: 'Education' },
  { name: 'GraduationCap', icon: GraduationCap, label: 'School' },
  { name: 'Library', icon: Library, label: 'Library' },
  { name: 'Globe', icon: Globe, label: 'Online' },
  { name: 'Languages', icon: Languages, label: 'Languages' },
  { name: 'Pen', icon: Pen, label: 'Writing' },
  { name: 'Newspaper', icon: Newspaper, label: 'News' },
  { name: 'Clapperboard', icon: Clapperboard, label: 'Movies' },
  { name: 'Music', icon: Music, label: 'Music' },
  { name: 'Gamepad2', icon: Gamepad2, label: 'Gaming' },
  { name: 'Palette', icon: Palette, label: 'Art' },
  { name: 'Trophy', icon: Trophy, label: 'Trophy' },
  { name: 'Medal', icon: Medal, label: 'Medal' },
  { name: 'Volleyball', icon: Volleyball, label: 'Sports' },
  { name: 'Footprints', icon: Footprints, label: 'Walking' },
  { name: 'Mountain', icon: Mountain, label: 'Hiking' },
  { name: 'Waves', icon: Waves, label: 'Swimming' },
  { name: 'Snowflake', icon: Snowflake, label: 'Winter' },
  { name: 'Sun', icon: Sun, label: 'Summer' },
  { name: 'Umbrella', icon: Umbrella, label: 'Umbrella' },
  { name: 'Briefcase', icon: Briefcase, label: 'Work' },
  { name: 'Rocket', icon: Rocket, label: 'Startup' },
  { name: 'Star', icon: Star, label: 'Favorites' },
  { name: 'Sparkles', icon: Sparkles, label: 'Special' },
  { name: 'Gift', icon: Gift, label: 'Gifts' },
  { name: 'PartyPopper', icon: PartyPopper, label: 'Party' },
  { name: 'Cake', icon: Cake, label: 'Birthday' },
  { name: 'Balloon', icon: Balloon, label: 'Celebration' },
  { name: 'Handshake', icon: Handshake, label: 'Business' },
  { name: 'Users', icon: Users, label: 'Family' },
  { name: 'UserRound', icon: UserRound, label: 'Personal' },
  { name: 'Crown', icon: Crown, label: 'Premium' },
  { name: 'Baby', icon: Baby, label: 'Kids' },
  { name: 'PawPrint', icon: PawPrint, label: 'Pets' },
  { name: 'Wrench', icon: Wrench, label: 'Repairs' },
  { name: 'Scissors', icon: Scissors, label: 'Personal care' },
  { name: 'Landmark', icon: Landmark, label: 'Banking' },
  { name: 'TrendingUp', icon: TrendingUp, label: 'Investments' },
  { name: 'CircleDollarSign', icon: CircleDollarSign, label: 'Income' },
  { name: 'PiggyBank', icon: PiggyBank, label: 'Savings' },
  { name: 'CreditCard', icon: CreditCard, label: 'Credit card' },
  { name: 'Receipt', icon: Receipt, label: 'Receipt' },
  { name: 'BarChart2', icon: BarChart2, label: 'Analytics' },
  { name: 'LineChart', icon: LineChart, label: 'Chart' },
  { name: 'DollarSign', icon: DollarSign, label: 'Dollar' },
  { name: 'Euro', icon: Euro, label: 'Euro' },
  { name: 'Coins', icon: Coins, label: 'Coins' },
  { name: 'Banknote', icon: Banknote, label: 'Cash' },
  { name: 'Diamond', icon: Diamond, label: 'Luxury' },
  { name: 'Gem', icon: Gem, label: 'Jewelry' },
  { name: 'Package', icon: Package, label: 'Package' },
  { name: 'Archive', icon: Archive, label: 'Archive' },
  { name: 'Box', icon: Box, label: 'Box' },
  { name: 'Boxes', icon: Boxes, label: 'Storage' },
  { name: 'Tag', icon: Tag, label: 'Tag' },
  { name: 'Tags', icon: Tags, label: 'Tags' },
  { name: 'Ticket', icon: Ticket, label: 'Ticket' },
  { name: 'QrCode', icon: QrCode, label: 'QR code' },
  { name: 'Leaf', icon: Leaf, label: 'Nature' },
  { name: 'Wallet', icon: Wallet, label: 'Other' },
];

const ICON_MAP = new Map(CATEGORY_ICONS.map((e) => [e.name, e.icon]));

function hexToRgb(hex: string): { r: number; g: number; b: number } | null {
  const clean = hex.replace('#', '');
  if (clean.length !== 6) return null;
  return {
    r: parseInt(clean.slice(0, 2), 16),
    g: parseInt(clean.slice(2, 4), 16),
    b: parseInt(clean.slice(4, 6), 16),
  };
}

function relativeLuminance(r: number, g: number, b: number): number {
  const toLinear = (c: number) => {
    const s = c / 255;
    return s <= 0.04045 ? s / 12.92 : Math.pow((s + 0.055) / 1.055, 2.4);
  };
  return 0.2126 * toLinear(r) + 0.7152 * toLinear(g) + 0.0722 * toLinear(b);
}

export function iconColorForBg(bgColor: string | null | undefined): string {
  if (!bgColor) return 'white';
  const rgb = hexToRgb(bgColor);
  if (!rgb) return 'white';
  const lum = relativeLuminance(rgb.r, rgb.g, rgb.b);
  return lum > 0.35 ? 'rgba(0,0,0,0.65)' : 'white';
}

interface CategoryIconProps {
  iconName: string | null | undefined;
  color: string | null | undefined;
  size?: number;
  containerSize?: number;
  borderRadius?: number;
  fallbackLetter?: string;
}

export function CategoryIcon({
  iconName,
  color,
  size = 16,
  containerSize = 32,
  borderRadius = 8,
  fallbackLetter,
}: CategoryIconProps) {
  const IconComponent = iconName ? ICON_MAP.get(iconName) : undefined;
  const iconColor = iconColorForBg(color);

  return (
    <div
      style={{
        width: containerSize,
        height: containerSize,
        borderRadius,
        background: color ?? 'var(--cream-darker)',
        display: 'flex',
        alignItems: 'center',
        justifyContent: 'center',
        flexShrink: 0,
      }}
    >
      {IconComponent ? (
        <IconComponent size={size} color={iconColor} strokeWidth={1.75} />
      ) : (
        <span style={{ fontSize: Math.round(containerSize * 0.4), fontWeight: 700, color: iconColor, lineHeight: 1 }}>
          {fallbackLetter ?? '?'}
        </span>
      )}
    </div>
  );
}
